import sounddevice as sd
import numpy as np

#generated by Gemini, prompt used: access linux mic audio python
# Audio configuration
SAMPLE_RATE = 44100  # Standard CD quality sampling rate
BLOCK_SIZE = 1024    # Number of frames per buffer block
CHANNELS = 1         # 1 for mono, 2 for stereo

def audio_callback(indata, frames, time, status):
    """This function is called for each audio block by sounddevice."""
    if status:
        print(f"Status Error: {status}", flush=True)
        
    # indata is a numpy array containing the microphone audio
    # Calculate Root Mean Square (RMS) to determine volume level
    volume_norm = np.linalg.norm(indata) * 10
    print(f"Mic Volume Level: {'|' * int(volume_norm)}", flush=True)

try:
    print("Accessing Linux microphone... Press Ctrl+C to stop.")
    # Open the microphone input stream
    with sd.InputStream(samplerate=SAMPLE_RATE,
                        blocksize=BLOCK_SIZE,
                        channels=CHANNELS,
                        callback=audio_callback):
        # Keep the main thread alive while the stream callback runs
        while True:
            sd.sleep(100)
            
except KeyboardInterrupt:
    print("\nStream stopped by user.")
except Exception as e:
    print(f"An error occurred: {e}")

