#import sounddevice as sd
#import numpy as np
#import rclpy
#import transcribe from nemo


#generated by gemini, edited to support inteneded function
#see audioTest.py for original

#class voiceProcessor(node): 
 #   def __init__(self):
  #      # Audio configuration
 #       self.SAMPLE_RATE = 44100  # Standard CD quality sampling rate
  #      self.BLOCK_SIZE = 1024    # Number of frames per buffer block
   #     self.CHANNELS = 1         # 1 for mono, 2 for stereo
    #    self.publisher_ = self.create_publisher(String, 'text', 10)
     #   self.srv = self.create_service(String, 'start_mic', self.start_mic_callback)
      #  self.oldMsg = String()
          

    #def audio_callback(indata, frames, time, status):
     #   """This function is called for each audio block by sounddevice."""
      #  if status:
       #     print(f"Status Error: {status}", flush=True)
        
    #def start_mic_callback(self):
     #   try:
      #  print("Accessing Linux microphone... Press Ctrl+C to stop.")
        # Open the microphone input stream
       # with sd.InputStream(samplerate=SAMPLE_RATE,
        #                blocksize=BLOCK_SIZE,
         #               channels=CHANNELS,
          #              callback=audio_callback):
            # Keep the main thread alive while the stream callback runs
        #while True:
         #   sd.sleep(100)
            
#except KeyboardInterrupt:
 #   print("\nStream stopped by user.")
#except Exception as e:
 #   print(f"An error occurred: {e}")



#def main(args=None):
 #   rclpy.init(args=args)

  #  voice_processor = voice_processor()

   # rclpy.spin(image_processor)

    #image_processor.destroy_node()
    #rclpy.shutdown()


#if __name__ == '__main__':
 #   main()

