import rclpy
import queue
from rclpy.node import Node
from std_msgs.msg import String
from cv_bridge import CvBridge #last 2 referenced by hiwonder's code
from sensor_msgs.msg import Image

from std_msgs.msg import String
import sounddevice as sd
import numpy as np



#generated by gemini, edited to support inteneded function
#see audioTest.py for original

class voiceProcessor(Node): 
    def __init__(self):
        # Audio configuration
        super().__init__('voiceProcessor')
        self.SAMPLE_RATE = 44100  # Standard CD quality sampling rate
        self.BLOCK_SIZE = 1024    # Number of frames per buffer block
        self.CHANNELS = 1         # 1 for mono, 2 for stereo
        self.publisher_ = self.create_publisher(String, 'text', 10)
        self.subscription = self.create_subscription(String,'command',self.command_callback,10)
        self.currentCommand = String()
        self.currentCommand.data = 'none'
        self.audioQueue = queue.Queue()
        self.stream = sd.InputStream(samplerate=self.SAMPLE_RATE,
                        blocksize=self.BLOCK_SIZE,
                        channels=self.CHANNELS,
                        callback=self.audio_callback)
       
            
    def command_callback(self, command):
        if(command.data == self.currentCommand.data): #cannot be same command currently have
            return
        elif(command.data == 'stop'):
            self.stream.stop(ignore_errors=True)
            print("microphone closed...")
        elif(command.data == 'start'):
            print("Accessing Linux microphone... Press Ctrl+C to stop.")
            self.stream.start()
            #Open the microphone input stream
            sd.sleep(100)
        
          

    def audio_callback(self, indata, frames, time, status):
        """This function is called for each audio block by sounddevice."""
        temp = indata[:]
        print(temp)
        if status:
            print(f"Status Error: {status}", flush=True)
        self.audioQueue.put(temp)
        
            
        

        
            
#except KeyboardInterrupt:
 #   print("\nStream stopped by user.")
#except Exception as e:
 #   print(f"An error occurred: {e}")



def main(args=None):
    rclpy.init(args=args)

    voice_processor = voiceProcessor()

    rclpy.spin(voice_processor)

    voice_processor.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()

